add_executable(BENCHMARK_quill_backend_throughput quill_backend_throughput.cpp)
set_common_compile_options(BENCHMARK_quill_backend_throughput)
target_link_libraries(BENCHMARK_quill_backend_throughput quill)

add_executable(BENCHMARK_quill_backend_throughput_no_buffering quill_backend_throughput_no_buffering.cpp)
set_common_compile_options(BENCHMARK_quill_backend_throughput_no_buffering)
target_link_libraries(BENCHMARK_quill_backend_throughput_no_buffering quill)

add_executable(BENCHMARK_quill_backend_throughput_macro_free quill_backend_throughput_macro_free.cpp)
set_common_compile_options(BENCHMARK_quill_backend_throughput_macro_free)
target_link_libraries(BENCHMARK_quill_backend_throughput_macro_free quill)

add_executable(BENCHMARK_quill_backend_throughput_json quill_backend_throughput_json.cpp)
set_common_compile_options(BENCHMARK_quill_backend_throughput_json)
target_link_libraries(BENCHMARK_quill_backend_throughput_json quill)

add_executable(BENCHMARK_quill_backend_throughput_json_named_args quill_backend_throughput_json_named_args.cpp)
set_common_compile_options(BENCHMARK_quill_backend_throughput_json_named_args)
target_link_libraries(BENCHMARK_quill_backend_throughput_json_named_args quill)

add_executable(BENCHMARK_quill_backend_throughput_filtered quill_backend_throughput_filtered.cpp)
set_common_compile_options(BENCHMARK_quill_backend_throughput_filtered)
target_link_libraries(BENCHMARK_quill_backend_throughput_filtered quill)

add_executable(BENCHMARK_quill_backend_throughput_two_producers quill_backend_throughput_two_producers.cpp)
set_common_compile_options(BENCHMARK_quill_backend_throughput_two_producers)
target_link_libraries(BENCHMARK_quill_backend_throughput_two_producers quill)
