name: Clang-MSVC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'scripts/**'

  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'scripts/**'

jobs:
  clang_msvc:
    runs-on: windows-2022
    strategy:
      matrix:
        build_type: [ Debug, Release ]
        std: [ 17 ]
    steps:
      - uses: actions/checkout@v4

      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "18.1"

      - name: Create Build Directory
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure with Clang-CL
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake -S . -B build -G "Ninja" \
          -DCMAKE_C_COMPILER=clang \
          -DCMAKE_CXX_COMPILER=clang++ \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_CXX_STANDARD=17 \
          -DQUILL_BUILD_TESTS=ON \
          -DQUILL_BUILD_EXAMPLES=ON \
          -DQUILL_VERBOSE_MAKEFILE=ON

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: |
          $threads = (Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors
          cmake --build . --config ${{matrix.build_type}} --parallel $threads

      - name: Test
        working-directory: ${{runner.workspace}}/build
        run: |
          ctest --build-config ${{matrix.build_type}} --output-on-failure
