name: Cross-Compile Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'scripts/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'scripts/**'

jobs:
  cross-compile:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            triplet: x86_64-linux-gnu
            compiler_package: g++
          - arch: arm64
            triplet: aarch64-linux-gnu
            compiler_package: g++-aarch64-linux-gnu
          - arch: armel
            triplet: arm-linux-gnueabi
            compiler_package: g++-arm-linux-gnueabi
          - arch: armhf
            triplet: arm-linux-gnueabihf
            compiler_package: g++-arm-linux-gnueabihf
          - arch: i386
            triplet: i686-linux-gnu
            compiler_package: g++-i686-linux-gnu
          - arch: ppc64el
            triplet: powerpc64le-linux-gnu
            compiler_package: g++-powerpc64le-linux-gnu
          - arch: riscv64
            triplet: riscv64-linux-gnu
            compiler_package: g++-riscv64-linux-gnu
          - arch: s390x
            triplet: s390x-linux-gnu
            compiler_package: g++-s390x-linux-gnu

    steps:
      - uses: actions/checkout@v4

      - name: Install cross-compiler
        run: |
          sudo apt-get update
          if [ "${{ matrix.arch }}" = "amd64" ]; then
            sudo apt-get install -y g++
          else
            sudo apt-get install -y ${{ matrix.compiler_package }}
          fi

      - name: Create Build Environment
        run: cmake -E make_directory ${{ runner.workspace }}/build

      - name: Configure CMake
        working-directory: ${{ runner.workspace }}/build
        env:
          CXX: ${{ matrix.triplet }}-g++
        run: |
          # For riscv64, add linker flags to resolve atomic builtins.
          if [ "${{ matrix.arch }}" = "riscv64" ] || [ "${{ matrix.arch }}" = "armel" ]; then
            LINK_FLAGS="-DCMAKE_EXE_LINKER_FLAGS='-latomic -static-libatomic'"
          else
            LINK_FLAGS=""
          fi
          cmake $GITHUB_WORKSPACE \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_STANDARD=17 \
            -DQUILL_BUILD_TESTS=OFF \
            -DQUILL_BUILD_EXAMPLES=ON \
            -DQUILL_VERBOSE_MAKEFILE=ON $LINK_FLAGS

      - name: Build
        working-directory: ${{ runner.workspace }}/build
        run: |
          threads=$(nproc)
          cmake --build . --config Release --parallel $threads
