name: Lintian Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lintian:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Debian Packaging Tools
        run: |
          sudo apt update
          sudo apt install -y lintian debhelper devscripts dh-make

      - name: Create Debian Source Package
        run: |
          export DEBFULLNAME="GitHub Actions"
          export DEBEMAIL="github-actions@noreply.com"
          # Use the -p flag to set the package name and version (<name>_<version> format)
          dh_make --single --yes --createorig -p quill_1.0-1
          # Force the version update using -b
          dch -b --newversion "1.0-1" "Automated CI build"
          dpkg-buildpackage -S -d
      
      - name: Run Lintian
        run: |
          # Lintian will now run on the generated source changes file
          lintian --pedantic --display-info --display-experimental --fail-on warning ../quill_1.0-1_source.changes
